### PR TITLE
fix: Only add new contact if it doesn't already exist

### LINKED ISSUE #22: Adding the same DID as a contact twice
If a DID contacts us and then we add the DID manually, this causes the label to disappear and the DID is displayed in the contact list instead of the originally received label.

### PR DESCRIPTION
**Pull request by frostyfrog**
fixes #22

### CODE REVIEW

File: src/pages/profile/messaging.ts [hunk 1]
```diff
@@ -46,7 +46,8 @@ class ContactListComponent
 
   async onAddContact() {
     if (this.newContact.did) {
-      ContactService.addContact(this.newContact as Contact)
+      if (!ContactService.getContact(this.newContact.did))
+        ContactService.addContact(this.newContact as Contact)
```
Comment (dbluhm) [inline src/pages/profile/messaging.ts:50]: I'm going to approve and merge this still but I strongly recommend always using brackets for multiline if statements. There's some fun anecdotes of someone coming in later to add more to the if body, add a properly indented line but fail to catch that the added indented line isn't a part of the if body.

**Review by dbluhm — APPROVED** [review]
